### ISSUE TITLE
Error de permisos en MySQL

### ISSUE THREAD

**Issue by alejandroalcazar** [GRISE-UPM/PROF-Testable-Design#1]
@odieste 

He intentado ejecutar:
```sql
INSERT INTO Counters (documentId) VALUES (0)
```

Para poder ejecutar la prueba que dice:
> La aplicación detecta correctamente que hay más de una fila en la tabla Counters.

Y me ha devuelto el siguiente error:
```
Error Code: 1142. INSERT command denied to user 'tema5'@'sri69.sri.fi.upm.es' for table 'Counters'
```

He desactivado safe updates:
```sql
SET SQL_SAFE_UPDATES = 0;
```

Lo cual me permite actualizar, pero el usuario sigue sin tener permiso para insertar. Por este motivo no puedo ejecutar la prueba mencionada anteriormente. **¿Puedes dar permisos al usuario `tema5` para este propósito?**

**Comment by odieste** [comment]
Hola Alejandro,

usando la clave de administrador podriais dar permiso de INSERT al usuario
tema5 (creo que me has enviado una URL incorrecta, pero eso no es
relevante). Sin embargo, pasa lo siguiente:

- La aplicación no inserta nada en la BD. Para qué es necesaria una
inserción?
- Incluso aunque la aplicación insertase algo, a nivel de unidad no parece
una buena idea tocar la BD para probar, entre otras cosas porque hay 15
compañeros más haciendo pruebas.
- Estamos trabajando a nivel de prueba de unidad. La clave es probar sin
usar la BD.

Saludos!

Oscar Dieste
Escuela Técnica Superior de Ingenieros Informáticos
Universidad Politécnica de Madrid
Campus de Montegancedo
28660 Boadilla del Monte (Spain)
phone: +34 91 067 2943‬    cell: +34 61 925 5259
skype: odieste    gtalk: oscar.dieste    iMessage:odieste@fi.upm.es

**Comment by PuppedToy** [comment]
Ah, había pensado hacer una prueba iniciando una transacción y haciendo rollback sin llegar a tocar la base de datos. 

Ahora mismo no tengo en mente cómo hacerlo sin usar ninguna base de datos. Lo que haría sería replicar la base de datos de forma local. ¿Es esa la solución que recomiendas? ¿O hay una mejor?
